name: root
channels:
  - pytorch
  - conda-forge
dependencies:
  - scipy
  - numpy
  - numba
  - pandas
  - jupyter
  - matplotlib
  - scikit-learn>=0.19
  - mahotas
  - scikit-image
  - keras>=2.0.0
  - h5py
  - tensorflow-gpu==1.6
  - cuda90
  - pytorch
  - torchvision
  - pip:
      - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/master
      - https://github.com/paris-saclay-cds/ssd_keras/archive/master.zip

