name: mars-craters
channels:
  - conda-forge
dependencies:
  - scipy
  - numpy
  - pandas
  - jupyter
  - matplotlib
  - scikit-learn
  - scikit-image
  - h5py
  - keras>=2.0.*
  - mahotas
  - pip:
    - https://api.github.com/repos/paris-saclay-cds/ramp-workflow/zipball/master
    - git+https://github.com/paris-saclay-cds/ssd_keras
